sheet_mapping = { 'name':"Full name",
  'date':"Today's Date",
  'school':"Graduate/Professional School", 
  'date_sign':"Today's Date",
  'student_signature_2':"Student's Signature", 
  'date_2':"Today's Date", 
  'course':"Course", 
  'course_title':"Course Title", 
  'class_number':" Class Number #", 
  'course_schedule':"Course Schedule", 
  'term':"Term", 
  'unique_id':"Duke Unique ID#",
  'email':"Duke e-mail address", 
  'degree':"Degree Pursuing", 
  'student_signature_1':"Student's Signature", 
  'phone':"Phone number", 
  'student_id':"Student ID#",
  "fall_1": "Fall 1",
  "fall_2": "Fall 2",
  "spring_1": "Spring 1", 
  "spring_2": "Spring 2",
  'credit': 'Credit',
  'audit': 'Audit',
  'departmental_code':'None',
  'signature_professor':'None',
}
  